import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {initialState,apply,quote,refund,status,view,type Action,type ShopState} from '../server/core.ts';
const seed=JSON.parse(readFileSync('initial-data.json','utf8'));
const setup=()=>{const s=initialState(seed);apply(s,{type:'address.save',customerId:1,label:'집',recipient:'테스트',phone:'010-1234-5678',street:'테스트로 1',detail:''});return s};
const place=(s:ShopState,a:Action)=>apply(s,{...a,confirmationKey:quote(s,a.customerId,Number(a.addressId),String(a.memo??''),String(a.coupon??'')).confirmationKey});
test('장바구니는 재고를 유지하고 첫 주문 확정에서만 차감하며 다른 고객의 부족 주문은 실패',()=>{const s=setup();apply(s,{type:'cart.add',customerId:1,sku:4,qty:1});assert.equal(s.products.find(p=>p.sku===4)?.stock,1);apply(s,{type:'address.save',customerId:2,label:'집',recipient:'가상',phone:'01012345678',street:'테스트로 2',detail:''});apply(s,{type:'cart.add',customerId:2,sku:4,qty:1});place(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:''});assert.equal(s.products.find(p=>p.sku===4)?.stock,0);assert.throws(()=>place(s,{type:'order.place',customerId:2,addressId:2,memo:'',coupon:''}),/재고/);assert.equal(s.users[2].cart.length,1);assert.equal(s.users[2].orders.length,0)});
test('무료 배송은 할인 전 30,000원 기준이고 전체 취소 시 주문 보존·쿠폰 복원·재고 복구',()=>{const s=setup();apply(s,{type:'cart.add',customerId:1,sku:1,qty:1});apply(s,{type:'cart.add',customerId:1,sku:3,qty:1});const q=quote(s,1,1,'문 앞',' welcome3000 ');assert.deepEqual([q.subtotal,q.discount,q.shipping,q.total],[31000,3000,0,28000]);const r=place(s,{type:'order.place',customerId:1,addressId:1,memo:'문 앞',coupon:' welcome3000 '});assert.equal(s.users[1].couponUsed,true);assert.equal(s.products.find(p=>p.sku===1)?.stock,2);apply(s,{type:'order.cancelAll',customerId:1,orderId:r.orderId});const o=s.users[1].orders[0];assert.equal(status(o),'전체 취소');assert.equal(refund(o),28000);assert.equal(s.users[1].couponUsed,false);assert.equal(s.products.find(p=>p.sku===1)?.stock,3);assert.equal(o.address.recipient,'테스트');assert.equal(s.users[1].orders.length,1)});
test('부분 취소 환급 누적 계산과 최종 전액 반환, 배송지 스냅샷',()=>{const s=setup();apply(s,{type:'cart.add',customerId:1,sku:1,qty:3});const r=place(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:'WELCOME3000'});apply(s,{type:'address.save',customerId:1,addressId:1,label:'수정',recipient:'바뀜',phone:'01012345678',street:'새 주소',detail:''});const o=s.users[1].orders[0];assert.equal(o.address.recipient,'테스트');apply(s,{type:'order.cancelItem',customerId:1,orderId:r.orderId,sku:1,qty:1});const once=refund(o);assert.equal(s.users[1].couponUsed,true);apply(s,{type:'order.cancelItem',customerId:1,orderId:r.orderId,sku:1,qty:1});assert.ok(refund(o)>once);apply(s,{type:'order.cancelItem',customerId:1,orderId:r.orderId,sku:1,qty:1});assert.equal(refund(o),o.total);assert.equal(s.users[1].couponUsed,false)});
test('다시 담기는 별도 주문이며 재고 부족이면 아무 줄도 추가하지 않음',()=>{const s=setup();apply(s,{type:'cart.add',customerId:1,sku:4,qty:1});const r=place(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:''});assert.throws(()=>apply(s,{type:'order.readd',customerId:1,orderId:r.orderId}),/다시 담을 수 없습니다/);assert.equal(s.users[1].cart.length,0);assert.equal(s.users[1].orders.length,1);apply(s,{type:'order.cancelAll',customerId:1,orderId:r.orderId});apply(s,{type:'order.readd',customerId:1,orderId:r.orderId});assert.equal(s.users[1].cart[0].qty,1);assert.equal(s.users[1].orders.length,1)});
test('고객별 저장 자료와 찜·나중에 구매 목록 분리',()=>{const s=setup();apply(s,{type:'favorite.toggle',customerId:1,sku:1});apply(s,{type:'cart.add',customerId:1,sku:1,qty:1});apply(s,{type:'saved.move',customerId:1,sku:1});assert.equal(view(s,1).user.saved.length,1);assert.equal(view(s,2).user.saved.length,0);assert.equal(view(s,2).user.favorites.length,0)});

test('찜에서 담기와 장바구니 선택·수량·합계·전체 비우기',()=>{const s=setup();apply(s,{type:'favorite.toggle',customerId:1,sku:1});assert.ok(s.users[1].favorites.includes(1));apply(s,{type:'cart.add',customerId:1,sku:1,qty:1});apply(s,{type:'cart.add',customerId:1,sku:1,qty:1});apply(s,{type:'cart.add',customerId:1,sku:3,qty:1});assert.deepEqual([s.users[1].cart.length,view(s,1).cartTotal,view(s,1).selectedTotal],[2,50000,50000]);apply(s,{type:'cart.select',customerId:1,sku:3,selected:false});assert.equal(view(s,1).selectedTotal,38000);apply(s,{type:'cart.qty',customerId:1,sku:1,qty:3});assert.equal(view(s,1).selectedTotal,57000);apply(s,{type:'cart.selectAll',customerId:1,selected:false});assert.equal(view(s,1).selectedTotal,0);apply(s,{type:'cart.remove',customerId:1,sku:3});apply(s,{type:'cart.clear',customerId:1});assert.equal(s.users[1].cart.length,0);assert.ok(s.users[1].favorites.includes(1))});
test('배송지 등록·수정·삭제·기본 지정과 가상 연락처 검증',()=>{const s=setup();const first=s.users[1].addresses[0];assert.equal(first.isDefault,true);apply(s,{type:'address.save',customerId:1,label:'회사',recipient:'가상',phone:'010 9876 5432',street:'테스트로 2',detail:'2층'});const second=s.users[1].addresses[1];apply(s,{type:'address.default',customerId:1,addressId:second.id});assert.equal(s.users[1].addresses[0].isDefault,false);apply(s,{type:'address.save',customerId:1,addressId:second.id,label:'회사2',recipient:'가상',phone:'01098765432',street:'테스트로 3',detail:''});assert.equal(second.label,'회사2');apply(s,{type:'address.delete',customerId:1,addressId:second.id});assert.equal(first.isDefault,true);assert.throws(()=>apply(s,{type:'address.save',customerId:1,label:'X',recipient:'Y',phone:'12',street:'Z',detail:''}),/연락처/)});
test('주문 검색·상태 필터와 CSV에서 배송 개인정보 제외',async()=>{const {orderSearch,csv}=await import('../server/core.ts');const s=setup();apply(s,{type:'cart.add',customerId:1,sku:1,qty:1});const r=place(s,{type:'order.place',customerId:1,addressId:1,memo:'비밀 메모',coupon:''});const order=s.users[1].orders[0];assert.equal(orderSearch([order],'데일리','전체').length,1);assert.equal(orderSearch([order],String(r.orderId),'취소 없음').length,1);apply(s,{type:'order.cancelAll',customerId:1,orderId:r.orderId});assert.equal(orderSearch([order],'','전체 취소').length,1);const output=csv(s,1,'데일리','전체 취소');assert.ok(output.includes('데일리 티셔츠'));assert.ok(!output.includes('테스트로'));assert.ok(!output.includes('비밀 메모'))});
test('최근 본 옵션 10개 제한과 전체 삭제',()=>{const s=setup();for(let sku=1;sku<=11;sku++)apply(s,{type:'recent.add',customerId:1,sku});assert.equal(s.users[1].recent.length,10);assert.equal(s.users[1].recent[0],11);assert.ok(!s.users[1].recent.includes(1));apply(s,{type:'recent.clear',customerId:1});assert.equal(s.users[1].recent.length,0)});
test('같은 금액의 선택 상품을 바꾸면 이전 확인 키로 주문할 수 없다',()=>{const s=setup();for(const sku of [1,2])apply(s,{type:'cart.add',customerId:1,sku,qty:1});apply(s,{type:'cart.select',customerId:1,sku:2,selected:false});const before=quote(s,1,1,'','');apply(s,{type:'cart.select',customerId:1,sku:1,selected:false});apply(s,{type:'cart.select',customerId:1,sku:2,selected:true});assert.equal(quote(s,1,1,'','').subtotal,before.subtotal);assert.throws(()=>apply(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:'',confirmationKey:before.confirmationKey}),/다시 확인/);assert.equal(s.users[1].orders.length,0);assert.equal(s.products.find(p=>p.sku===2)?.stock,2);const after=quote(s,1,1,'','');apply(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:'',confirmationKey:after.confirmationKey});assert.equal(s.users[1].orders[0].items[0].sku,2)});
test('배송지를 수정하면 이전 확인 키로 주문할 수 없다',()=>{const s=setup();apply(s,{type:'cart.add',customerId:1,sku:1,qty:1});const before=quote(s,1,1,'','');apply(s,{type:'address.save',customerId:1,addressId:1,label:'집',recipient:'테스트',phone:'01012345678',street:'수정된 주소',detail:''});assert.throws(()=>apply(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:'',confirmationKey:before.confirmationKey}),/다시 확인/);assert.equal(s.users[1].orders.length,0);assert.throws(()=>apply(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:''}),/다시 확인/);const after=quote(s,1,1,'','');apply(s,{type:'order.place',customerId:1,addressId:1,memo:'',coupon:'',confirmationKey:after.confirmationKey});assert.equal(s.users[1].orders[0].address.street,'수정된 주소')});
